[package]
name = "j_growing_project_package_crates_modules"
version = "0.1.0"
authors = ["nerioalfonso"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
